# Day 5 - Pandas: Basic Dataset Analysis

This notebook demonstrates the use of Pandas for loading, inspecting, filtering, and analyzing a student dataset.

In [48]:
import pandas as pd

## 1. Loading the Dataset

The `read_csv()` function is used to load the CSV dataset into a Pandas DataFrame.

In [49]:
df = pd.read_csv("student_data.csv")

## 2. Viewing the Dataset

The `head()` function displays the first five rows of the dataset, while `tail()` displays the last five rows.

In [ ]:
print("First 5 rows:") 
display(df.head()) #df.head(n) returns first n rows

print("Last 5 rows:")
display(df.tail()) #df.tail(n) returns last n rows

First 5 rows:

,Student_ID,Name,Department,Age,Attendance,Python_Marks,ML_Marks,Projects
0,101,Aarav,CSE,20.0,92.0,85.0,88.0,3.0
1,102,Diya,AIML,21.0,87.0,78.0,91.0,2.0
2,103,Rohan,CSE,NaN,76.0,69.0,74.0,1.0
3,104,Meera,AIML,20.0,NaN,92.0,89.0,4.0
4,105,Kabir,CSE,22.0,81.0,NaN,72.0,2.0

Last 5 rows:

,Student_ID,Name,Department,Age,Attendance,Python_Marks,ML_Marks,Projects
15,116,Nisha,AIML,20.0,88.0,82.0,NaN,3.0
16,117,Manav,CSE,21.0,72.0,67.0,70.0,2.0
17,118,Tara,AIML,20.0,NaN,91.0,93.0,4.0
18,119,Neil,CSE,22.0,83.0,77.0,75.0,2.0
19,120,Riya,AIML,21.0,90.0,NaN,89.0,3.0

## 3. Dataset Dimensions

The `shape` attribute returns the number of rows and columns present in the DataFrame.

In [51]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 20
Number of columns: 8

## 4. Dataset Information

The `info()` function provides information about the DataFrame, including column names, data types, and the number of non-null values.

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    20 non-null     int64
 1   Name          20 non-null     str
 2   Department    20 non-null     str
 3   Age           17 non-null     float64
 4   Attendance    17 non-null     float64
 5   Python_Marks  17 non-null     float64
 6   ML_Marks      18 non-null     float64
 7   Projects      19 non-null     float64
dtypes: float64(5), int64(1), str(2)
memory usage: 1.4 KB


## 5. Checking Missing Values

The `isnull()` function identifies missing values, and `sum()` counts their number.
`isnull().sum()` counts the missing values in each column.

In [53]:
df.isnull().sum()

Student_ID      0
Name            0
Department      0
Age             3
Attendance      3
Python_Marks    3
ML_Marks        2
Projects        1
dtype: int64

## 6. Filtering Data

Filtering allows us to select specific rows from the DataFrame based on conditions.

Different filtering conditions are used below to select students based on their marks, attendance, and department.

In [54]:
print("Students with Python marks > 80:")
display(df[df["Python_Marks"] > 80])

print("Students with attendance > 85:")
display(df[df["Attendance"] > 85])

print("AIML students:")
display(df[df["Department"] == "AIML"])

Students with Python marks > 80:

,Student_ID,Name,Department,Age,Attendance,Python_Marks,ML_Marks,Projects
0,101,Aarav,CSE,20.0,92.0,85.0,88.0,3.0
3,104,Meera,AIML,20.0,NaN,92.0,89.0,4.0
5,106,Anaya,AIML,21.0,95.0,88.0,94.0,5.0
9,110,Sara,AIML,20.0,91.0,86.0,90.0,4.0
13,114,Kiara,AIML,22.0,96.0,94.0,97.0,5.0
15,116,Nisha,AIML,20.0,88.0,82.0,NaN,3.0
17,118,Tara,AIML,20.0,NaN,91.0,93.0,4.0

Students with attendance > 85:

,Student_ID,Name,Department,Age,Attendance,Python_Marks,ML_Marks,Projects
0,101,Aarav,CSE,20.0,92.0,85.0,88.0,3.0
1,102,Diya,AIML,21.0,87.0,78.0,91.0,2.0
5,106,Anaya,AIML,21.0,95.0,88.0,94.0,5.0
7,108,Isha,AIML,NaN,89.0,79.0,85.0,3.0
9,110,Sara,AIML,20.0,91.0,86.0,90.0,4.0
13,114,Kiara,AIML,22.0,96.0,94.0,97.0,5.0
15,116,Nisha,AIML,20.0,88.0,82.0,NaN,3.0
19,120,Riya,AIML,21.0,90.0,NaN,89.0,3.0

AIML students:

,Student_ID,Name,Department,Age,Attendance,Python_Marks,ML_Marks,Projects
1,102,Diya,AIML,21.0,87.0,78.0,91.0,2.0
3,104,Meera,AIML,20.0,NaN,92.0,89.0,4.0
5,106,Anaya,AIML,21.0,95.0,88.0,94.0,5.0
7,108,Isha,AIML,NaN,89.0,79.0,85.0,3.0
9,110,Sara,AIML,20.0,91.0,86.0,90.0,4.0
11,112,Myra,AIML,21.0,84.0,NaN,87.0,3.0
13,114,Kiara,AIML,22.0,96.0,94.0,97.0,5.0
15,116,Nisha,AIML,20.0,88.0,82.0,NaN,3.0
17,118,Tara,AIML,20.0,NaN,91.0,93.0,4.0
19,120,Riya,AIML,21.0,90.0,NaN,89.0,3.0

### Filtering with Multiple Conditions

The `&` operator is used when both conditions must be true, while the `|` operator is used when either condition can be true.

In [55]:
print("Students with Python > 80 AND ML > 80:")
display(df[(df["Python_Marks"] > 80) & (df["ML_Marks"] > 80)])

Students with Python > 80 AND ML > 80:

,Student_ID,Name,Department,Age,Attendance,Python_Marks,ML_Marks,Projects
0,101,Aarav,CSE,20.0,92.0,85.0,88.0,3.0
3,104,Meera,AIML,20.0,NaN,92.0,89.0,4.0
5,106,Anaya,AIML,21.0,95.0,88.0,94.0,5.0
9,110,Sara,AIML,20.0,91.0,86.0,90.0,4.0
13,114,Kiara,AIML,22.0,96.0,94.0,97.0,5.0
17,118,Tara,AIML,20.0,NaN,91.0,93.0,4.0

In [56]:
print("Students with Python > 85 OR ML > 90:")
display(df[(df["Python_Marks"] > 85) | (df["ML_Marks"] > 90)])

Students with Python > 85 OR ML > 90:

,Student_ID,Name,Department,Age,Attendance,Python_Marks,ML_Marks,Projects
1,102,Diya,AIML,21.0,87.0,78.0,91.0,2.0
3,104,Meera,AIML,20.0,NaN,92.0,89.0,4.0
5,106,Anaya,AIML,21.0,95.0,88.0,94.0,5.0
9,110,Sara,AIML,20.0,91.0,86.0,90.0,4.0
13,114,Kiara,AIML,22.0,96.0,94.0,97.0,5.0
17,118,Tara,AIML,20.0,NaN,91.0,93.0,4.0

## 7. Summary Statistics

The `describe()` function provides statistical information for the numerical columns, including count, mean, standard deviation, minimum, maximum, and quartile values.

In [57]:
print("Summary statistics:")
display(df.describe())

Summary statistics:

       Student_ID        Age  Attendance  Python_Marks   ML_Marks   Projects
count    20.00000  17.000000   17.000000     17.000000  18.000000  19.000000
mean    110.50000  20.823529   82.882353     77.117647  81.000000   2.684211
std       5.91608   0.808957    9.433202     11.789202  11.530012   1.293257
min     101.00000  20.000000   65.000000     55.000000  61.000000   1.000000
25%     105.75000  20.000000   76.000000     69.000000  72.250000   2.000000
50%     110.50000  21.000000   84.000000     78.000000  86.000000   3.000000
75%     115.25000  21.000000   90.000000     86.000000  89.750000   3.500000
max     120.00000  22.000000   96.000000     94.000000  97.000000   5.000000

### Individual Column Statistics

Specific statistical measures can also be calculated for individual columns using functions such as `mean()`, `max()`, and `min()`.

In [58]:
print("Python marks statistics:")
print(df["Python_Marks"].describe())

print("\nAverage Python marks:", df["Python_Marks"].mean())
print("Average ML marks:", df["ML_Marks"].mean())

print("\nHighest Python marks:", df["Python_Marks"].max())
print("Highest ML marks:", df["ML_Marks"].max())

print("\nLowest Python marks:", df["Python_Marks"].min())
print("Lowest ML marks:", df["ML_Marks"].min())

Python marks statistics:
count    17.000000
mean     77.117647
std      11.789202
min      55.000000
25%      69.000000
50%      78.000000
75%      86.000000
max      94.000000
Name: Python_Marks, dtype: float64

Average Python marks: 77.11764705882354
Average ML marks: 81.0

Highest Python marks: 94.0
Highest ML marks: 97.0

Lowest Python marks: 55.0
Lowest ML marks: 61.0

## 8. Conclusion

The dataset was successfully loaded and analyzed using Pandas. The analysis included viewing the dataset, checking its dimensions and information, identifying missing values, filtering records using different conditions, and generating summary statistics.